[package]
name = "vifeed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[registries.crates-io]
protocol = "sparse"

[dependencies]
crossterm = "0.26.1"
feed-rs = "1.3.0"
tui = "0.19.0"
ureq = "2.6.2"
